### ISSUE TITLE
Publish library to PyPI

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-ephys-utils#2]
# User story
As a user, I want the package published to PyPI, so I can easily add it to other projects.

# Acceptance criteria
- [ ] When a PR is merged into the main branch, then the package gets tagged and published to PyPI.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
The code do this is commented out in the tag_and_publish.yml file in the .github/workflows directory. Whenever the codebase is ready to be deployed, we just need to un-comment those lines.

**Comment by jsiegle** [comment]
@jtyoung84 I think we are ready for this
